name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file SettlementManager/Dockerfile --tag settlementmanager:$(date +%s)

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          publish_dir: ./SettlementManager/wwwroot # Укажите директорию, где находятся ваши скомпилированные файлы
          github_token: ${{ secrets.GITHUB_TOKEN }}
